databases:
  - name: blog_project_xuk0
    plan: free
    databaseName: blog_project_xuk0
    user: blog_project_xuk0_user

services:
  - type: web
    plan: free
    name: blog_project_xuk0
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn blog_project_xuk0.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_project_xuk0
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
