# Generated by Django 5.1 on 2024-08-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
