# Generated by Django 5.1 on 2024-08-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('Draft', 'Draft')], default='active', max_length=10),
        ),
    ]
