# Generated by Django 5.0.8 on 2024-08-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_cover_blog_cover_url_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default='add comments here', max_length=300),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Please add your name', max_length=100),
        ),
    ]
