# Generated by Django 5.1 on 2024-08-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_url',
            field=models.CharField(max_length=200),
        ),
    ]
